apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-1
  name: node-1
  namespace: astrid-kube
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: node-1
  clusterIP: None
status:
  loadBalancer: {}
