apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-6-pv-volume
  namespace: astrid-kube
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/node-6-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-6-pv-claim
  namespace: astrid-kube
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
