apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-0
  name: node-0
  namespace: astrid-kube
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: node-0
  clusterIP: None
status:
  loadBalancer: {}
